# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shopcek-landing-page

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://test/
        username: ${{ secrets.AzureAppService_ContainerUsername_1a57f1ce1b8d4858b8e411beb688ee64 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_20716e37152748b9a2616df125283f49 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: test/${{ secrets.AzureAppService_ContainerUsername_1a57f1ce1b8d4858b8e411beb688ee64 }}/landing-page:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shopcek-landing-page'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6902718082624434ad58f6ef83964398 }}
        images: 'test/${{ secrets.AzureAppService_ContainerUsername_1a57f1ce1b8d4858b8e411beb688ee64 }}/landing-page:${{ github.sha }}'